### ISSUE TITLE
/etc/default/netns breaks custom settings

### ISSUE THREAD

**Issue by f3flight** [Jamesits/systemd-named-netns#15]
Currently if you need only some of the options you run into an issue that default netns file defines everything and is always included, so you have to either undefine these variables orcomment /etc/default/netns each time after running install script.

Need to either specify in /etc/default/netns how to properly create custom config (i.e. have to "unset" all unneeded variables from default config) or rework sourcing.

**Comment by Jamesits** [comment]
The current default config is rather a "defensive" config to ensure everything's working without any manual config. I don't think there is possibility to undefine the variables since the config files are evaluated with systemd's `EnvironmentFile` directive rather than a shell. 

However we can assume the user will always provide a netns name, so maybe we just leave the default config as a template, rather than including it in every service?

**Comment by f3flight** [comment]
@Jamesits makes sense, alternatively we can just comment out all the settings in the config and write there that if these settings are uncommented they will be used as defaults, so uncomment only if necessary. Up to you, I just commented out all the lines to fix my issue locally.

**Comment by Jamesits** [comment]
LGTM
